# Dockerfile.hello-pi
FROM cross-pi AS builder

COPY basic_pub_sub /code/

ENV BIN_DIR /tmp/bin
ENV BUILD_DIR /code/build

RUN mkdir -p $BIN_DIR && \
  mkdir -p $BUILD_DIR && \
  cd /code/build && \
  . /opt/poky/4.0.10/environment-setup-cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi && \
  cmake -DCMAKE_BUILD_TYPE="Debug" .. && \
  cmake --build . --config "Debug"  && \
  cp -r ${BUILD_DIR}/basic_pub_sub ${BIN_DIR} 

FROM scratch
COPY --from=builder /tmp/bin /
